### PR TITLE
Combining tests to one file.

### PR DESCRIPTION
**Pull request by bgphipps**
@sheeley @brekk @mgloystein review please.

Just combined the tests into one file.

### CODE REVIEW

**Comment by brekk** [comment]
INSANITY.

:+1:

**Comment by mgloystein** [comment]
This one ought to make the test succeed, right?

**Comment by bgphipps** [comment]
@mgloystein not 100%. Let me update circleci with this branch. hold off for a moment.

**Comment by mgloystein** [comment]
%100?

**Comment by bgphipps** [comment]
@mgloystein all tests run now, but we have some failing.

**Comment by sheeley** [comment]
Nice

**Pull request merged**
